parameters:
    librinfo:
        configuration:
            templates:
                show:
                    stats: LibrinfoEmailBundle:CRUD:show_field_stats.html.twig
######  Email ##########
        Librinfo\EmailBundle\Entity\Email:
            Sonata\AdminBundle\Datagrid\ListMapper:
                remove: [createdAt]
                add:
                    field_to: ~
                    field_subject: ~
                    sent: ~
                    _actions:
                        type: actions
                        label: Action
                        actions:
                            show: ~
                            edit: ~
                            delete: ~
                            duplicate:
                                template: LibrinfoEmailBundle:CRUD:list__action_duplicate.html.twig
                                route: duplicate
                            send:
                                template: LibrinfoEmailBundle:CRUD:list__action_send.html.twig

                    _options:
                        fieldsOrder:
                            - field_to
                            - field_subject
                            - sent
                    _export_format:
                        csv: [ field_from, field_to, field_subject, field_cc, field_bcc, textContent, createdAt, updatedAt]
                        xls: csv
                        json: csv
                        xml: csv
            Sonata\AdminBundle\Show\ShowMapper:
                add:
                   default:
                        form_group_general:
                            field_to: ~
                            field_cc: ~
                            field_bcc: ~

                            textContent:
                                type: textarea
                                label: Content
                            attachments: ~
                        form_group_tracking:
                            stats:
                                type: stats
                        _options:
                            groupsOrder:
                            - form_group_general
                            - form_group_tracking
                            - from_group_misc
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            field_from:
                                type: text
                            field_to:
                                type: text
                            organisms:
                                type: sonata_type_model_autocomplete
                                property: name
                                multiple: true
                                required: false
                                _options:
                                    admin_code: crm.organism
                            positions:
                                type: sonata_type_model_autocomplete
                                property: [contact.name, organism.name]
                                multiple: true
                                required: false
                            contacts:
                                type: sonata_type_model_autocomplete
                                property: [firstname, name]
                                multiple: true
                                required: false
                                _options:
                                    admin_code: crm.contact
                            field_subject:
                                type: text
                                required: false
                            field_cc:
                                type: text
                                required: false
                            field_bcc:
                                type: text
                                required: false
                            template:
                                attr:
                                    class: template_select
                            content:
                                type: textarea
                                attr:
                                    class: tinymce
                                    data-theme: advanced
                            attachments:
                                type: dropzone
                                required: false
                            _options:
                                fieldsOrder:
                                    - field_from
                                    - field_to
                                    - field_cc
                                    - field_bcc
                                    - organisms
                                    - positions
                                    - contacts
                                    - field_subject
                                    - template
                                    - content
                                    - attachments
                        form_group_options:
                            isTemplate:
                                type: checkbox
                                required: false
                            newTemplateName:
                                type: text
                                required: false
                            isTest:
                                type: checkbox
                                required: false
                                attr:
                                    class: is_test
                            testAddress:
                                type: text
                                required: false
                            tracking:
                                type: checkbox
                                required: false
                    _options:
                        tabsOrder: [ form_group_general, form_group_specifics ]
            Sonata\AdminBundle\Datagrid\DatagridMapper:
                add:
                    field_to: ~
                    field_subject: ~
                    content: ~
                    sent: ~
                    createdAt: ~
                    updatedAt: ~
                    createdBy: ~
                    updatedBy: ~
                    _options:
                        fieldsOrder:
                            - field_to
                            - field_subject

########## EmailTemplate ##########
        Librinfo\EmailBundle\Entity\EmailTemplate:
            Sonata\AdminBundle\Show\ShowMapper:
                _copy: Sonata\AdminBundle\Form\FormMapper
            Sonata\AdminBundle\Form\FormMapper:
                add:
                    form_group_general:
                        '':
                            name:
                                type: text
                            content:
                                type: textarea
                                attr:
                                    class: tinymce
                                    data-theme: advanced
                    _options:
                            tabsOrder: [form_group_general, form_group_specifics]
            Sonata\AdminBundle\Datagrid\ListMapper:
                remove: [createdAt]
                add:
                    name: ~
                    content: ~