sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
        sonata.admin.block.search_result:

sonata_admin:
    dashboard:
        groups:
            Email:
                label: Email
                items:
                    - email.email
                    - email.email_template
    security:
        handler: librinfo.security_bundle.sonata.voter
